on:
  push:
    branches-ignore:
    - master

name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: fbscotta369/prueba-gha:${{ github.sha }}

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
    -
      name: deploy to cluster
      uses: myrotvorets/kubectl-action@2.0.0
#      uses: steebchen/kubectl@v2.1.1
#      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
#        command: -n prueba set image --record deployment/prueba-gha prueba-gha=fbscotta369/prueba-gha:${{ github.sha }}
        args: set image --record deployment/prueba-gha prueba-gha=fbscotta369/prueba-gha:${{ github.sha }}
    - 
      name: verify deployment
      uses: myrotvorets/kubectl-action@2.0.0
#      uses: steebchen/kubectl@v2.1.1
#      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#        KUBECTL_VERSION: "1.28"
      with:
#        config: ${{ secrets.KUBE_CONFIG_DATA }}
#        command: -n prueba rollout status deployment/prueba-gha
        args: rollout status deployment/prueba-gha


